### ISSUE TITLE
Confusing variable name without proper capitalization

### ISSUE THREAD

**Issue by piprett** [Allymonies/Krypton#1]
https://github.com/Allymonies/Krypton/blob/c94a582c6b4acc2c4d480859cf6c36529871fb75/init.lua#L14

I do not like the casing on this function name. It makes it hard to read.
Context: Kristify/kristly#2

**Comment by PatriikPlays** [comment]
For inspiration see:
https://github.com/Allymonies/Krypton/blob/c94a582c6b4acc2c4d480859cf6c36529871fb75/init.lua#L47

**Comment by piprett** [comment]
extremely correct** code
